//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQUEST.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IT_ASSET_MANAGEMENTEntities : DbContext
    {
        public IT_ASSET_MANAGEMENTEntities()
            : base("name=IT_ASSET_MANAGEMENTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_assesories> tbl_assesories { get; set; }
        public virtual DbSet<tbl_buy_reason> tbl_buy_reason { get; set; }
        public virtual DbSet<tbl_categories> tbl_categories { get; set; }
        public virtual DbSet<tbl_cost_section> tbl_cost_section { get; set; }
        public virtual DbSet<tbl_costcenter> tbl_costcenter { get; set; }
        public virtual DbSet<tbl_device_types> tbl_device_types { get; set; }
        public virtual DbSet<tbl_doc_group> tbl_doc_group { get; set; }
        public virtual DbSet<tbl_doc_type> tbl_doc_type { get; set; }
        public virtual DbSet<tbl_document> tbl_document { get; set; }
        public virtual DbSet<tbl_hw_assets> tbl_hw_assets { get; set; }
        public virtual DbSet<tbl_hw_log_case> tbl_hw_log_case { get; set; }
        public virtual DbSet<tbl_hw_options_addon> tbl_hw_options_addon { get; set; }
        public virtual DbSet<tbl_hw_sw_standard> tbl_hw_sw_standard { get; set; }
        public virtual DbSet<tbl_hw_terminate> tbl_hw_terminate { get; set; }
        public virtual DbSet<tbl_incident_case> tbl_incident_case { get; set; }
        public virtual DbSet<tbl_incident_part> tbl_incident_part { get; set; }
        public virtual DbSet<tbl_Incident_status> tbl_Incident_status { get; set; }
        public virtual DbSet<tbl_it_staff> tbl_it_staff { get; set; }
        public virtual DbSet<tbl_pc_standards> tbl_pc_standards { get; set; }
        public virtual DbSet<tbl_pc_sw_standard> tbl_pc_sw_standard { get; set; }
        public virtual DbSet<tbl_req_allow_status> tbl_req_allow_status { get; set; }
        public virtual DbSet<tbl_req_types> tbl_req_types { get; set; }
        public virtual DbSet<tbl_request_status> tbl_request_status { get; set; }
        public virtual DbSet<tbl_staff_member> tbl_staff_member { get; set; }
        public virtual DbSet<tbl_status_hw> tbl_status_hw { get; set; }
        public virtual DbSet<tbl_supplier> tbl_supplier { get; set; }
        public virtual DbSet<tbl_sw_assets> tbl_sw_assets { get; set; }
        public virtual DbSet<tbl_sw_type> tbl_sw_type { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
        public virtual DbSet<tbl_year_document_number> tbl_year_document_number { get; set; }
        public virtual DbSet<TblLocalTable> TblLocalTables { get; set; }
        public virtual DbSet<tbl_configure> tbl_configure { get; set; }
        public virtual DbSet<View_costcenter> View_costcenter { get; set; }
        public virtual DbSet<View_device_type> View_device_type { get; set; }
        public virtual DbSet<View_document> View_document { get; set; }
        public virtual DbSet<View_hw_assets> View_hw_assets { get; set; }
        public virtual DbSet<View_hw_options_addon> View_hw_options_addon { get; set; }
        public virtual DbSet<View_hw_sw_standard> View_hw_sw_standard { get; set; }
        public virtual DbSet<View_inc_status> View_inc_status { get; set; }
        public virtual DbSet<View_incident_all> View_incident_all { get; set; }
        public virtual DbSet<View_incident_case> View_incident_case { get; set; }
        public virtual DbSet<View_it_open_by> View_it_open_by { get; set; }
        public virtual DbSet<View_pc_standards> View_pc_standards { get; set; }
        public virtual DbSet<View_pc_sw_standard> View_pc_sw_standard { get; set; }
        public virtual DbSet<View_staff_member> View_staff_member { get; set; }
        public virtual DbSet<View_sw_assets> View_sw_assets { get; set; }
        public virtual DbSet<tbl_Req_Applicant> tbl_Req_Applicant { get; set; }
        public virtual DbSet<tbl_Req_Authen> tbl_Req_Authen { get; set; }
        public virtual DbSet<tbl_Req_AF> tbl_Req_AF { get; set; }
        public virtual DbSet<tbl_AF_STATUS> tbl_AF_STATUS { get; set; }
        public virtual DbSet<tbl_Req_Navi_HR> tbl_Req_Navi_HR { get; set; }
        public virtual DbSet<tbl_Req_Program> tbl_Req_Program { get; set; }
        public virtual DbSet<tbl_Req_SharDrive> tbl_Req_SharDrive { get; set; }
        public virtual DbSet<View_Req_AF> View_Req_AF { get; set; }
        public virtual DbSet<View_Req_Navi_HR_Trace> View_Req_Navi_HR_Trace { get; set; }
        public virtual DbSet<View_Req_PG> View_Req_PG { get; set; }
        public virtual DbSet<View_Req_PG_Trace> View_Req_PG_Trace { get; set; }
        public virtual DbSet<View_Req_SD> View_Req_SD { get; set; }
        public virtual DbSet<View_Req_AF_Trace> View_Req_AF_Trace { get; set; }
        public virtual DbSet<View_Req_SD_Trace> View_Req_SD_Trace { get; set; }
        public virtual DbSet<tbl_Req_Nav> tbl_Req_Nav { get; set; }
        public virtual DbSet<tbl_section> tbl_section { get; set; }
        public virtual DbSet<View_Req_NAV> View_Req_NAV { get; set; }
        public virtual DbSet<View_Req_NAV_Trace> View_Req_NAV_Trace { get; set; }
        public virtual DbSet<View_Req_Navi_HR> View_Req_Navi_HR { get; set; }
        public virtual DbSet<View_Req_PDJCOST01_Trace> View_Req_PDJCOST01_Trace { get; set; }
        public virtual DbSet<tbl_Req_PDJCOST01> tbl_Req_PDJCOST01 { get; set; }
        public virtual DbSet<View_Req_PDJCOST01> View_Req_PDJCOST01 { get; set; }
        public virtual DbSet<tbl_Req_PDJMINI02> tbl_Req_PDJMINI02 { get; set; }
        public virtual DbSet<View_Req_PDJMINI02> View_Req_PDJMINI02 { get; set; }
        public virtual DbSet<View_Req_PDJMINI02_Trace> View_Req_PDJMINI02_Trace { get; set; }
    
        public virtual int AutoAF(ObjectParameter req_AF_CODE, string allow_STATUS, string uSER_NO, string aF_Site, string aF_Folder, string aF_STATUS_ID, string rEQ_STATUS, string aF_Note, string aF_REQUESTER, Nullable<System.DateTime> aF_DATE, string aF_APPROVER, Nullable<System.DateTime> date_APPROVER)
        {
            var allow_STATUSParameter = allow_STATUS != null ?
                new ObjectParameter("Allow_STATUS", allow_STATUS) :
                new ObjectParameter("Allow_STATUS", typeof(string));
    
            var uSER_NOParameter = uSER_NO != null ?
                new ObjectParameter("USER_NO", uSER_NO) :
                new ObjectParameter("USER_NO", typeof(string));
    
            var aF_SiteParameter = aF_Site != null ?
                new ObjectParameter("AF_Site", aF_Site) :
                new ObjectParameter("AF_Site", typeof(string));
    
            var aF_FolderParameter = aF_Folder != null ?
                new ObjectParameter("AF_Folder", aF_Folder) :
                new ObjectParameter("AF_Folder", typeof(string));
    
            var aF_STATUS_IDParameter = aF_STATUS_ID != null ?
                new ObjectParameter("AF_STATUS_ID", aF_STATUS_ID) :
                new ObjectParameter("AF_STATUS_ID", typeof(string));
    
            var rEQ_STATUSParameter = rEQ_STATUS != null ?
                new ObjectParameter("REQ_STATUS", rEQ_STATUS) :
                new ObjectParameter("REQ_STATUS", typeof(string));
    
            var aF_NoteParameter = aF_Note != null ?
                new ObjectParameter("AF_Note", aF_Note) :
                new ObjectParameter("AF_Note", typeof(string));
    
            var aF_REQUESTERParameter = aF_REQUESTER != null ?
                new ObjectParameter("AF_REQUESTER", aF_REQUESTER) :
                new ObjectParameter("AF_REQUESTER", typeof(string));
    
            var aF_DATEParameter = aF_DATE.HasValue ?
                new ObjectParameter("AF_DATE", aF_DATE) :
                new ObjectParameter("AF_DATE", typeof(System.DateTime));
    
            var aF_APPROVERParameter = aF_APPROVER != null ?
                new ObjectParameter("AF_APPROVER", aF_APPROVER) :
                new ObjectParameter("AF_APPROVER", typeof(string));
    
            var date_APPROVERParameter = date_APPROVER.HasValue ?
                new ObjectParameter("Date_APPROVER", date_APPROVER) :
                new ObjectParameter("Date_APPROVER", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AutoAF", req_AF_CODE, allow_STATUSParameter, uSER_NOParameter, aF_SiteParameter, aF_FolderParameter, aF_STATUS_IDParameter, rEQ_STATUSParameter, aF_NoteParameter, aF_REQUESTERParameter, aF_DATEParameter, aF_APPROVERParameter, date_APPROVERParameter);
        }
    
        public virtual int AutoProgram(ObjectParameter req_PG_CODE, string uSER_NO, Nullable<System.DateTime> pG_DATE, string pG_Work, string pG_Problem, string pG_Requirement, string pG_Frequency, Nullable<System.DateTime> pG_Date_start, string rEQ_STATUS, string pG_APPROVER, Nullable<System.DateTime> pG_APPROVER_DATE)
        {
            var uSER_NOParameter = uSER_NO != null ?
                new ObjectParameter("USER_NO", uSER_NO) :
                new ObjectParameter("USER_NO", typeof(string));
    
            var pG_DATEParameter = pG_DATE.HasValue ?
                new ObjectParameter("PG_DATE", pG_DATE) :
                new ObjectParameter("PG_DATE", typeof(System.DateTime));
    
            var pG_WorkParameter = pG_Work != null ?
                new ObjectParameter("PG_Work", pG_Work) :
                new ObjectParameter("PG_Work", typeof(string));
    
            var pG_ProblemParameter = pG_Problem != null ?
                new ObjectParameter("PG_Problem", pG_Problem) :
                new ObjectParameter("PG_Problem", typeof(string));
    
            var pG_RequirementParameter = pG_Requirement != null ?
                new ObjectParameter("PG_Requirement", pG_Requirement) :
                new ObjectParameter("PG_Requirement", typeof(string));
    
            var pG_FrequencyParameter = pG_Frequency != null ?
                new ObjectParameter("PG_Frequency", pG_Frequency) :
                new ObjectParameter("PG_Frequency", typeof(string));
    
            var pG_Date_startParameter = pG_Date_start.HasValue ?
                new ObjectParameter("PG_Date_start", pG_Date_start) :
                new ObjectParameter("PG_Date_start", typeof(System.DateTime));
    
            var rEQ_STATUSParameter = rEQ_STATUS != null ?
                new ObjectParameter("REQ_STATUS", rEQ_STATUS) :
                new ObjectParameter("REQ_STATUS", typeof(string));
    
            var pG_APPROVERParameter = pG_APPROVER != null ?
                new ObjectParameter("PG_APPROVER", pG_APPROVER) :
                new ObjectParameter("PG_APPROVER", typeof(string));
    
            var pG_APPROVER_DATEParameter = pG_APPROVER_DATE.HasValue ?
                new ObjectParameter("PG_APPROVER_DATE", pG_APPROVER_DATE) :
                new ObjectParameter("PG_APPROVER_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AutoProgram", req_PG_CODE, uSER_NOParameter, pG_DATEParameter, pG_WorkParameter, pG_ProblemParameter, pG_RequirementParameter, pG_FrequencyParameter, pG_Date_startParameter, rEQ_STATUSParameter, pG_APPROVERParameter, pG_APPROVER_DATEParameter);
        }
    
        public virtual int AutoSharDrive(ObjectParameter req_SD_CODE, string allow_STATUS, string iD_Authen, string uSER_NO, Nullable<System.DateTime> sD_DATE, string sD_Drive, string sD_Folder, string sD_Note, string sD_REQUESTER, string sD_APPROVER, Nullable<System.DateTime> date_APPROVER, string rEQ_STATUS)
        {
            var allow_STATUSParameter = allow_STATUS != null ?
                new ObjectParameter("Allow_STATUS", allow_STATUS) :
                new ObjectParameter("Allow_STATUS", typeof(string));
    
            var iD_AuthenParameter = iD_Authen != null ?
                new ObjectParameter("ID_Authen", iD_Authen) :
                new ObjectParameter("ID_Authen", typeof(string));
    
            var uSER_NOParameter = uSER_NO != null ?
                new ObjectParameter("USER_NO", uSER_NO) :
                new ObjectParameter("USER_NO", typeof(string));
    
            var sD_DATEParameter = sD_DATE.HasValue ?
                new ObjectParameter("SD_DATE", sD_DATE) :
                new ObjectParameter("SD_DATE", typeof(System.DateTime));
    
            var sD_DriveParameter = sD_Drive != null ?
                new ObjectParameter("SD_Drive", sD_Drive) :
                new ObjectParameter("SD_Drive", typeof(string));
    
            var sD_FolderParameter = sD_Folder != null ?
                new ObjectParameter("SD_Folder", sD_Folder) :
                new ObjectParameter("SD_Folder", typeof(string));
    
            var sD_NoteParameter = sD_Note != null ?
                new ObjectParameter("SD_Note", sD_Note) :
                new ObjectParameter("SD_Note", typeof(string));
    
            var sD_REQUESTERParameter = sD_REQUESTER != null ?
                new ObjectParameter("SD_REQUESTER", sD_REQUESTER) :
                new ObjectParameter("SD_REQUESTER", typeof(string));
    
            var sD_APPROVERParameter = sD_APPROVER != null ?
                new ObjectParameter("SD_APPROVER", sD_APPROVER) :
                new ObjectParameter("SD_APPROVER", typeof(string));
    
            var date_APPROVERParameter = date_APPROVER.HasValue ?
                new ObjectParameter("Date_APPROVER", date_APPROVER) :
                new ObjectParameter("Date_APPROVER", typeof(System.DateTime));
    
            var rEQ_STATUSParameter = rEQ_STATUS != null ?
                new ObjectParameter("REQ_STATUS", rEQ_STATUS) :
                new ObjectParameter("REQ_STATUS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AutoSharDrive", req_SD_CODE, allow_STATUSParameter, iD_AuthenParameter, uSER_NOParameter, sD_DATEParameter, sD_DriveParameter, sD_FolderParameter, sD_NoteParameter, sD_REQUESTERParameter, sD_APPROVERParameter, date_APPROVERParameter, rEQ_STATUSParameter);
        }
    
        public virtual int AutoNaviHR(ObjectParameter req_Navi_HR_CODE, string uSER_NO, string allow_STATUS, string navi_HR_User_Log_In, string navi_HR_Detail, string rEQ_STATUS, string navi_HR_REQUESTER, Nullable<System.DateTime> navi_HR_REQUESTER_DATE, string navi_HR_APPROVER, Nullable<System.DateTime> navi_HR_APPROVER_DATE)
        {
            var uSER_NOParameter = uSER_NO != null ?
                new ObjectParameter("USER_NO", uSER_NO) :
                new ObjectParameter("USER_NO", typeof(string));
    
            var allow_STATUSParameter = allow_STATUS != null ?
                new ObjectParameter("Allow_STATUS", allow_STATUS) :
                new ObjectParameter("Allow_STATUS", typeof(string));
    
            var navi_HR_User_Log_InParameter = navi_HR_User_Log_In != null ?
                new ObjectParameter("Navi_HR_User_Log_In", navi_HR_User_Log_In) :
                new ObjectParameter("Navi_HR_User_Log_In", typeof(string));
    
            var navi_HR_DetailParameter = navi_HR_Detail != null ?
                new ObjectParameter("Navi_HR_Detail", navi_HR_Detail) :
                new ObjectParameter("Navi_HR_Detail", typeof(string));
    
            var rEQ_STATUSParameter = rEQ_STATUS != null ?
                new ObjectParameter("REQ_STATUS", rEQ_STATUS) :
                new ObjectParameter("REQ_STATUS", typeof(string));
    
            var navi_HR_REQUESTERParameter = navi_HR_REQUESTER != null ?
                new ObjectParameter("Navi_HR_REQUESTER", navi_HR_REQUESTER) :
                new ObjectParameter("Navi_HR_REQUESTER", typeof(string));
    
            var navi_HR_REQUESTER_DATEParameter = navi_HR_REQUESTER_DATE.HasValue ?
                new ObjectParameter("Navi_HR_REQUESTER_DATE", navi_HR_REQUESTER_DATE) :
                new ObjectParameter("Navi_HR_REQUESTER_DATE", typeof(System.DateTime));
    
            var navi_HR_APPROVERParameter = navi_HR_APPROVER != null ?
                new ObjectParameter("Navi_HR_APPROVER", navi_HR_APPROVER) :
                new ObjectParameter("Navi_HR_APPROVER", typeof(string));
    
            var navi_HR_APPROVER_DATEParameter = navi_HR_APPROVER_DATE.HasValue ?
                new ObjectParameter("Navi_HR_APPROVER_DATE", navi_HR_APPROVER_DATE) :
                new ObjectParameter("Navi_HR_APPROVER_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AutoNaviHR", req_Navi_HR_CODE, uSER_NOParameter, allow_STATUSParameter, navi_HR_User_Log_InParameter, navi_HR_DetailParameter, rEQ_STATUSParameter, navi_HR_REQUESTERParameter, navi_HR_REQUESTER_DATEParameter, navi_HR_APPROVERParameter, navi_HR_APPROVER_DATEParameter);
        }
    
        public virtual int AutoNAV(ObjectParameter req_NAV_CODE, string uSER_NO, string allow_STATUS, string sECTION_ID, Nullable<System.DateTime> dATE_NAV, string nAV_Detail, string nAV_DOC, string nAV_APPROVER, Nullable<System.DateTime> date_APPROVER, string rEQ_STATUS)
        {
            var uSER_NOParameter = uSER_NO != null ?
                new ObjectParameter("USER_NO", uSER_NO) :
                new ObjectParameter("USER_NO", typeof(string));
    
            var allow_STATUSParameter = allow_STATUS != null ?
                new ObjectParameter("Allow_STATUS", allow_STATUS) :
                new ObjectParameter("Allow_STATUS", typeof(string));
    
            var sECTION_IDParameter = sECTION_ID != null ?
                new ObjectParameter("SECTION_ID", sECTION_ID) :
                new ObjectParameter("SECTION_ID", typeof(string));
    
            var dATE_NAVParameter = dATE_NAV.HasValue ?
                new ObjectParameter("DATE_NAV", dATE_NAV) :
                new ObjectParameter("DATE_NAV", typeof(System.DateTime));
    
            var nAV_DetailParameter = nAV_Detail != null ?
                new ObjectParameter("NAV_Detail", nAV_Detail) :
                new ObjectParameter("NAV_Detail", typeof(string));
    
            var nAV_DOCParameter = nAV_DOC != null ?
                new ObjectParameter("NAV_DOC", nAV_DOC) :
                new ObjectParameter("NAV_DOC", typeof(string));
    
            var nAV_APPROVERParameter = nAV_APPROVER != null ?
                new ObjectParameter("NAV_APPROVER", nAV_APPROVER) :
                new ObjectParameter("NAV_APPROVER", typeof(string));
    
            var date_APPROVERParameter = date_APPROVER.HasValue ?
                new ObjectParameter("Date_APPROVER", date_APPROVER) :
                new ObjectParameter("Date_APPROVER", typeof(System.DateTime));
    
            var rEQ_STATUSParameter = rEQ_STATUS != null ?
                new ObjectParameter("REQ_STATUS", rEQ_STATUS) :
                new ObjectParameter("REQ_STATUS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AutoNAV", req_NAV_CODE, uSER_NOParameter, allow_STATUSParameter, sECTION_IDParameter, dATE_NAVParameter, nAV_DetailParameter, nAV_DOCParameter, nAV_APPROVERParameter, date_APPROVERParameter, rEQ_STATUSParameter);
        }
    
        public virtual int AutoPDJ01(ObjectParameter req_PDJ01_CODE, string uSER_NO, string rEQ_STATUS, string allow_STATUS, string color_Picture, string quotation, string spec_Sheet, string produce_Prices, string product_Analysis, string line_Drawing, string pDJ01_REQUESTER, Nullable<System.DateTime> pDJ01_REQUESTER_DATE, string pDJ01_APPROVER, Nullable<System.DateTime> pDJ01_APPROVER_DATE, string aPPROVER_MANAGER, Nullable<System.DateTime> dATE_APPROVER_MANAGER)
        {
            var uSER_NOParameter = uSER_NO != null ?
                new ObjectParameter("USER_NO", uSER_NO) :
                new ObjectParameter("USER_NO", typeof(string));
    
            var rEQ_STATUSParameter = rEQ_STATUS != null ?
                new ObjectParameter("REQ_STATUS", rEQ_STATUS) :
                new ObjectParameter("REQ_STATUS", typeof(string));
    
            var allow_STATUSParameter = allow_STATUS != null ?
                new ObjectParameter("Allow_STATUS", allow_STATUS) :
                new ObjectParameter("Allow_STATUS", typeof(string));
    
            var color_PictureParameter = color_Picture != null ?
                new ObjectParameter("Color_Picture", color_Picture) :
                new ObjectParameter("Color_Picture", typeof(string));
    
            var quotationParameter = quotation != null ?
                new ObjectParameter("Quotation", quotation) :
                new ObjectParameter("Quotation", typeof(string));
    
            var spec_SheetParameter = spec_Sheet != null ?
                new ObjectParameter("Spec_Sheet", spec_Sheet) :
                new ObjectParameter("Spec_Sheet", typeof(string));
    
            var produce_PricesParameter = produce_Prices != null ?
                new ObjectParameter("Produce_Prices", produce_Prices) :
                new ObjectParameter("Produce_Prices", typeof(string));
    
            var product_AnalysisParameter = product_Analysis != null ?
                new ObjectParameter("Product_Analysis", product_Analysis) :
                new ObjectParameter("Product_Analysis", typeof(string));
    
            var line_DrawingParameter = line_Drawing != null ?
                new ObjectParameter("Line_Drawing", line_Drawing) :
                new ObjectParameter("Line_Drawing", typeof(string));
    
            var pDJ01_REQUESTERParameter = pDJ01_REQUESTER != null ?
                new ObjectParameter("PDJ01_REQUESTER", pDJ01_REQUESTER) :
                new ObjectParameter("PDJ01_REQUESTER", typeof(string));
    
            var pDJ01_REQUESTER_DATEParameter = pDJ01_REQUESTER_DATE.HasValue ?
                new ObjectParameter("PDJ01_REQUESTER_DATE", pDJ01_REQUESTER_DATE) :
                new ObjectParameter("PDJ01_REQUESTER_DATE", typeof(System.DateTime));
    
            var pDJ01_APPROVERParameter = pDJ01_APPROVER != null ?
                new ObjectParameter("PDJ01_APPROVER", pDJ01_APPROVER) :
                new ObjectParameter("PDJ01_APPROVER", typeof(string));
    
            var pDJ01_APPROVER_DATEParameter = pDJ01_APPROVER_DATE.HasValue ?
                new ObjectParameter("PDJ01_APPROVER_DATE", pDJ01_APPROVER_DATE) :
                new ObjectParameter("PDJ01_APPROVER_DATE", typeof(System.DateTime));
    
            var aPPROVER_MANAGERParameter = aPPROVER_MANAGER != null ?
                new ObjectParameter("APPROVER_MANAGER", aPPROVER_MANAGER) :
                new ObjectParameter("APPROVER_MANAGER", typeof(string));
    
            var dATE_APPROVER_MANAGERParameter = dATE_APPROVER_MANAGER.HasValue ?
                new ObjectParameter("DATE_APPROVER_MANAGER", dATE_APPROVER_MANAGER) :
                new ObjectParameter("DATE_APPROVER_MANAGER", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AutoPDJ01", req_PDJ01_CODE, uSER_NOParameter, rEQ_STATUSParameter, allow_STATUSParameter, color_PictureParameter, quotationParameter, spec_SheetParameter, produce_PricesParameter, product_AnalysisParameter, line_DrawingParameter, pDJ01_REQUESTERParameter, pDJ01_REQUESTER_DATEParameter, pDJ01_APPROVERParameter, pDJ01_APPROVER_DATEParameter, aPPROVER_MANAGERParameter, dATE_APPROVER_MANAGERParameter);
        }
    
        public virtual int AutoPDJMINI02(ObjectParameter req_PDJ02_CODE, string allow_STATUS, string rEQ_STATUS, string uSER_NO, string sample_Pdj02, string proto_Pdj02, string prototypeInfrom, string cHM_Pdj02, string pDJ02_REQUESTER, Nullable<System.DateTime> pDJ02_REQUESTER_DATE, string pDJ02_APPROVER, Nullable<System.DateTime> pDJ02_APPROVER_DATE)
        {
            var allow_STATUSParameter = allow_STATUS != null ?
                new ObjectParameter("Allow_STATUS", allow_STATUS) :
                new ObjectParameter("Allow_STATUS", typeof(string));
    
            var rEQ_STATUSParameter = rEQ_STATUS != null ?
                new ObjectParameter("REQ_STATUS", rEQ_STATUS) :
                new ObjectParameter("REQ_STATUS", typeof(string));
    
            var uSER_NOParameter = uSER_NO != null ?
                new ObjectParameter("USER_NO", uSER_NO) :
                new ObjectParameter("USER_NO", typeof(string));
    
            var sample_Pdj02Parameter = sample_Pdj02 != null ?
                new ObjectParameter("Sample_Pdj02", sample_Pdj02) :
                new ObjectParameter("Sample_Pdj02", typeof(string));
    
            var proto_Pdj02Parameter = proto_Pdj02 != null ?
                new ObjectParameter("Proto_Pdj02", proto_Pdj02) :
                new ObjectParameter("Proto_Pdj02", typeof(string));
    
            var prototypeInfromParameter = prototypeInfrom != null ?
                new ObjectParameter("PrototypeInfrom", prototypeInfrom) :
                new ObjectParameter("PrototypeInfrom", typeof(string));
    
            var cHM_Pdj02Parameter = cHM_Pdj02 != null ?
                new ObjectParameter("CHM_Pdj02", cHM_Pdj02) :
                new ObjectParameter("CHM_Pdj02", typeof(string));
    
            var pDJ02_REQUESTERParameter = pDJ02_REQUESTER != null ?
                new ObjectParameter("PDJ02_REQUESTER", pDJ02_REQUESTER) :
                new ObjectParameter("PDJ02_REQUESTER", typeof(string));
    
            var pDJ02_REQUESTER_DATEParameter = pDJ02_REQUESTER_DATE.HasValue ?
                new ObjectParameter("PDJ02_REQUESTER_DATE", pDJ02_REQUESTER_DATE) :
                new ObjectParameter("PDJ02_REQUESTER_DATE", typeof(System.DateTime));
    
            var pDJ02_APPROVERParameter = pDJ02_APPROVER != null ?
                new ObjectParameter("PDJ02_APPROVER", pDJ02_APPROVER) :
                new ObjectParameter("PDJ02_APPROVER", typeof(string));
    
            var pDJ02_APPROVER_DATEParameter = pDJ02_APPROVER_DATE.HasValue ?
                new ObjectParameter("PDJ02_APPROVER_DATE", pDJ02_APPROVER_DATE) :
                new ObjectParameter("PDJ02_APPROVER_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AutoPDJMINI02", req_PDJ02_CODE, allow_STATUSParameter, rEQ_STATUSParameter, uSER_NOParameter, sample_Pdj02Parameter, proto_Pdj02Parameter, prototypeInfromParameter, cHM_Pdj02Parameter, pDJ02_REQUESTERParameter, pDJ02_REQUESTER_DATEParameter, pDJ02_APPROVERParameter, pDJ02_APPROVER_DATEParameter);
        }
    }
}
