//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQUEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_device_types
    {
        public int DEV_ID { get; set; }
        public string DEV_CODE { get; set; }
        public string DEV_DESCRIPTION { get; set; }
        public string PREFIX { get; set; }
        public int LAST_DIGIT { get; set; }
    }
}
