//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQUEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Req_Program
    {
        public string Req_PG_CODE { get; set; }
        public string USER_NO { get; set; }
        public Nullable<System.DateTime> PG_DATE { get; set; }
        public string PG_Work { get; set; }
        public string PG_Problem { get; set; }
        public string PG_Requirement { get; set; }
        public string PG_Frequency { get; set; }
        public Nullable<System.DateTime> PG_Date_start { get; set; }
        public string PG_APPROVER { get; set; }
        public Nullable<System.DateTime> PG_APPROVER_DATE { get; set; }
        public string PG_APPROVER_IT { get; set; }
        public Nullable<System.DateTime> Date_APPROVER_IT { get; set; }
        public string Req_OPEN_BY { get; set; }
        public Nullable<System.DateTime> Req_OPEN_DATE { get; set; }
        public Nullable<System.DateTime> Req_ASSIGN_TO_DATE { get; set; }
        public string Req_ASSIGN_TO { get; set; }
        public string REQ_STATUS { get; set; }
        public string Req_CLOSE { get; set; }
        public Nullable<System.DateTime> Req_CLOSE_DATE { get; set; }
        public string Req_BILL_NO { get; set; }
        public Nullable<System.DateTime> Req_BILL_DATE { get; set; }
        public Nullable<float> Req_COST { get; set; }
        public string USER_CREATE { get; set; }
        public string USER_UPDATE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<System.DateTime> Req_SUBMIT_DATE { get; set; }
    }
}
