//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQUEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_configure
    {
        public int ID { get; set; }
        public string DOC_LOCATION { get; set; }
        public string PIC_LOCATION { get; set; }
        public string AUD_LOCATION { get; set; }
        public string INC_NO_PRF { get; set; }
        public string INC_NO_YEAR { get; set; }
        public string REQ_NO_PRF { get; set; }
        public string REQ_NO_YEAR { get; set; }
        public string AUD_NO_PRF { get; set; }
        public string AUD_NO_YEAR { get; set; }
        public int INC_NO_RUN { get; set; }
        public int REQ_NO_RUN { get; set; }
        public int AUD_NO_RUN { get; set; }
    }
}
