//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQUEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_incident_part
    {
        public int IS_ID { get; set; }
        public string IS_PICTURE_PART { get; set; }
        public string IS_PURCHASE_PART { get; set; }
        public string IS_MA_PART { get; set; }
        public string IS_MANUAL_PART { get; set; }
        public string IS_CONTRACT_PART { get; set; }
        public string IS_OTH_PART { get; set; }
    }
}
