//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQUEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_doc_type
    {
        public int DOC_TYPE { get; set; }
        public string DOC_TYPE_DESC { get; set; }
        public string DOC_LOCATION { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
