//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQUEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hw_terminate
    {
        public string HW_CODE { get; set; }
        public string HW_TERMIANATE { get; set; }
        public string HW_TERM_DATE { get; set; }
        public string HW_REASON_REMARK { get; set; }
        public string HW_TERM_APPROVE { get; set; }
        public string USER_CREATE { get; set; }
        public string USER_UPDATE { get; set; }
        public string CREATE_DATE { get; set; }
        public string UPDATE_DATE { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
