//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQUEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hw_assets
    {
        public int HW_ID { get; set; }
        public string HW_CODE { get; set; }
        public string DEV_CODE { get; set; }
        public string HW_ASSET { get; set; }
        public string HW_ASSET_NAME { get; set; }
        public string HW_YEAR { get; set; }
        public string HW_START_DATE { get; set; }
        public string HW_END_DATE { get; set; }
        public string HW_BRAND { get; set; }
        public string HW_MODEL { get; set; }
        public string HW_SERIAL { get; set; }
        public string PC_CODE { get; set; }
        public string COST_ID { get; set; }
        public string HW_SERVICE_TAG { get; set; }
        public string HW_DESC_SHORT { get; set; }
        public string HW_DESCRIPT_LONG { get; set; }
        public string HW_PURCHASE_NO { get; set; }
        public string HW_PURCHASE_DATE { get; set; }
        public string HW_PICTURE { get; set; }
        public string SUPPLIER { get; set; }
        public int HW_WARANTEE { get; set; }
        public int HW_WAR_YEAR { get; set; }
        public string HW_WAR_END_DATE { get; set; }
        public string DOC_NO { get; set; }
        public string HW_RENT { get; set; }
        public int ST_ID { get; set; }
        public string HW_REMARK { get; set; }
        public string HW_IP { get; set; }
        public string HW_MAX_ADDRESS { get; set; }
        public string USER_CREATE { get; set; }
        public string USER_UPDATE { get; set; }
        public string CREATE_DATE { get; set; }
        public string UPDATE_DATE { get; set; }
        public string HW_DEPT_NAME { get; set; }
        public string HW_INSTALL_DATE { get; set; }
        public string HW_OWNNER { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
