//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQUEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hw_log_case
    {
        public string HW_CODE { get; set; }
        public System.DateTime HW_TX_DATE { get; set; }
        public string HW_LOG_CASE { get; set; }
        public string HW_LOG_DESCRIPTION { get; set; }
        public string USER_CREATE { get; set; }
        public string USER_UPDATE { get; set; }
        public string CREATE_DATE { get; set; }
        public string UPDATE_DATE { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
