//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQUEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_buy_reason
    {
        public int REASON_ID { get; set; }
        public string REASON_DESCRIPTION { get; set; }
    }
}
