//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQUEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_supplier
    {
        public string SUPPLIER { get; set; }
        public string SUPPLIER_NAME { get; set; }
        public string SUPPLIER_TYPE { get; set; }
        public string SUPPLIER_CONTACT { get; set; }
        public string SUPPLIER_PHONE_1 { get; set; }
        public string SUPPLIER_PHONE_2 { get; set; }
        public string SUPPLIER_NOTE { get; set; }
        public string SUPPLIER_STATUS { get; set; }
        public string SUPPLIER_ADDRESS { get; set; }
        public string SUPPLIER_SHORT { get; set; }
        public string SUPPLIER_AREA { get; set; }
        public string SUPPLIER_MAIL { get; set; }
    }
}
