//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQUEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_year_document_number
    {
        public string Year { get; set; }
        public string DocType { get; set; }
        public string PrefixText { get; set; }
        public Nullable<float> StartNumber { get; set; }
        public Nullable<float> LastNumber { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string USER_CREATE { get; set; }
        public string USER_UPDATE { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
