//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQUEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_req_types
    {
        public string REQ_TYPE { get; set; }
        public string REQ_TYPE_DESC { get; set; }
        public string REQ_PREFIX { get; set; }
    }
}
