//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQUEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_it_staff
    {
        public string EMP_NO { get; set; }
        public string IT_NAME { get; set; }
        public string IT_SURNAME { get; set; }
        public string IT_SECTION { get; set; }
        public string IT_EXTENSION { get; set; }
    }
}
