//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQUEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        public int USER_ID { get; set; }
        public string USER_NO { get; set; }
        public string USER_PASSWORD { get; set; }
        public string USER_NAME { get; set; }
        public Nullable<System.DateTime> USER_LOGIN_TIME { get; set; }
        public string USER_LOGIN_FLAG { get; set; }
        public string USER_STATUS { get; set; }
        public string USER_EMAIL { get; set; }
        public string USER_EXTENSION { get; set; }
        public string USER_ROLE { get; set; }
        public string NAME_ENG { get; set; }
        public string PROSITION { get; set; }
        public string DEPARTMENT { get; set; }
    }
}
