//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQUEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_staff_member
    {
        public int EMP_ID { get; set; }
        public string EMP_NO { get; set; }
        public string EMP_NAME { get; set; }
        public string EMP_SURNAME { get; set; }
        public string COST_ID { get; set; }
        public string EMP_SECTION { get; set; }
        public string EMP_EXTENSION { get; set; }
        public string EMP_LOCATION { get; set; }
    }
}
