//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQUEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sw_type
    {
        public int DEV_SW_ID { get; set; }
        public string DEV_SW_CODE { get; set; }
        public string DEV_SW_DESCRIPTION { get; set; }
        public Nullable<decimal> DEV_SW_EST_PRICE { get; set; }
    }
}
