//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQUEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLocalTable
    {
        public bool PrintPreview { get; set; }
        public string LastUserID { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public string LastLang { get; set; }
    }
}
