//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQUEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_incident_all
    {
        public string INC_CODE { get; set; }
        public System.DateTime INC_DATE { get; set; }
        public string INC_TOPIC { get; set; }
        public string INC_REQUESTER { get; set; }
        public string INC_OPEN_BY { get; set; }
        public string INC_ASSIGN_TO { get; set; }
        public string INC_STATUS { get; set; }
        public string INC_CATEGORIES { get; set; }
        public string INC_BILL_NO { get; set; }
        public Nullable<System.DateTime> INC_BILL_DATE { get; set; }
        public Nullable<System.DateTime> INC_OPEN_DATE { get; set; }
        public Nullable<System.DateTime> INC_DUE_DATE { get; set; }
        public Nullable<System.DateTime> INC_RESOLVE_DATE { get; set; }
        public string INC_DESCRIPTION { get; set; }
        public string HW_CODE { get; set; }
        public Nullable<System.DateTime> INC_CLOSE_DATE { get; set; }
        public string COST_ID { get; set; }
        public Nullable<System.DateTime> INC_SUBMIT_DATE { get; set; }
        public Nullable<System.DateTime> INC_ASSIGN_DATE { get; set; }
        public string COST_SECTION { get; set; }
        public Nullable<System.DateTime> INC_CANCEL_DATE { get; set; }
        public string STA_DESCRIPTION { get; set; }
        public string EMP_NO { get; set; }
        public string IT_NAME { get; set; }
        public string IT_SURNAME { get; set; }
        public string EMP_ASSIGN { get; set; }
        public string EMP_ASSIGN_NAME { get; set; }
        public string EMP_ASSIGN_SURNAME { get; set; }
        public string Expr1 { get; set; }
        public string HW_ASSET { get; set; }
        public string HW_ASSET_NAME { get; set; }
        public string USER_NAME { get; set; }
        public string USER_NO { get; set; }
        public string INC_COMMENTS { get; set; }
        public string CATE_DESC { get; set; }
    }
}
