//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQUEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_inc_status
    {
        public string INC_CODE { get; set; }
        public System.DateTime INC_DATE { get; set; }
        public string INC_TOPIC { get; set; }
        public string INC_REQUESTER { get; set; }
        public string INC_STATUS { get; set; }
        public string STA_DESCRIPTION { get; set; }
        public string INC_DESCRIPTION { get; set; }
        public string USER_NO { get; set; }
        public string USER_NAME { get; set; }
    }
}
