//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQUEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Req_PDJCOST01
    {
        public string Req_PDJ01_CODE { get; set; }
        public string REQ_STATUS { get; set; }
        public string STA_DESCRIPTION { get; set; }
        public string USER_NO { get; set; }
        public string USER_NAME { get; set; }
        public string NAME_ENG { get; set; }
        public string PROSITION { get; set; }
        public string DEPARTMENT { get; set; }
        public string USER_EXTENSION { get; set; }
        public string Color_Picture { get; set; }
        public string Quotation { get; set; }
        public string Spec_Sheet { get; set; }
        public string Produce_Prices { get; set; }
        public string Product_Analysis { get; set; }
        public string Line_Drawing { get; set; }
        public string PDJ01_REQUESTER { get; set; }
        public string NAME_REQUESTER { get; set; }
        public string PROSITION_REQUESTER { get; set; }
        public string DEPARTMENT_REQUESTER { get; set; }
        public string EXTENSION_REQUESTER { get; set; }
        public Nullable<System.DateTime> PDJ01_REQUESTER_DATE { get; set; }
        public string Allow_DESCRIPTION { get; set; }
    }
}
