//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQUEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Req_SD
    {
        public string Req_SD_CODE { get; set; }
        public string USER_NO { get; set; }
        public string USER_NAME { get; set; }
        public string NAME_ENG { get; set; }
        public string PROSITION { get; set; }
        public string DEPARTMENT { get; set; }
        public string USER_EXTENSION { get; set; }
        public Nullable<System.DateTime> SD_DATE { get; set; }
        public string SD_Drive { get; set; }
        public string SD_Folder { get; set; }
        public string SD_Note { get; set; }
        public string SD_REQUESTER { get; set; }
        public string NAME_REQUESTER { get; set; }
        public string PROSITION_REQUESTER { get; set; }
        public string DEPARTMENT_REQUESTER { get; set; }
        public string EXTENSION_REQUESTER { get; set; }
        public string Allow_DESCRIPTION { get; set; }
        public string Authen_DESCRIPTION { get; set; }
        public string STA_DESCRIPTION { get; set; }
        public string REQ_STATUS { get; set; }
    }
}
