//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQUEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Req_PG
    {
        public string Req_PG_CODE { get; set; }
        public string USER_NO { get; set; }
        public string USER_NAME { get; set; }
        public string NAME_ENG { get; set; }
        public string PROSITION { get; set; }
        public string DEPARTMENT { get; set; }
        public string USER_EXTENSION { get; set; }
        public Nullable<System.DateTime> PG_DATE { get; set; }
        public string PG_Work { get; set; }
        public string PG_Problem { get; set; }
        public string PG_Requirement { get; set; }
        public string PG_Frequency { get; set; }
        public Nullable<System.DateTime> PG_Date_start { get; set; }
        public string STA_DESCRIPTION { get; set; }
        public string REQ_STATUS { get; set; }
    }
}
