//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQUEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_pc_standards
    {
        public int PC_ID { get; set; }
        public string PC_CODE { get; set; }
        public string PC_YEAR { get; set; }
        public string PC_DESCRIPTION { get; set; }
        public string PC_REMARK { get; set; }
        public byte[] upsize_ts { get; set; }
    }
}
