//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQUEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Req_Navi_HR
    {
        public string Req_Navi_HR_CODE { get; set; }
        public string USER_NO { get; set; }
        public string USER_NAME { get; set; }
        public string NAME_ENG { get; set; }
        public string PROSITION { get; set; }
        public string DEPARTMENT { get; set; }
        public string USER_EXTENSION { get; set; }
        public string Allow_STATUS { get; set; }
        public string Navi_HR_User_Log_In { get; set; }
        public string Navi_HR_Detail { get; set; }
        public Nullable<System.DateTime> Navi_HR_REQUESTER_DATE { get; set; }
        public string Navi_HR_REQUESTER { get; set; }
        public string NAME_REQUESTER { get; set; }
        public string PROSITION_REQUESTER { get; set; }
        public string DEPARTMENT_REQUESTER { get; set; }
        public string EXTENSION_REQUESTER { get; set; }
        public string REQ_STATUS { get; set; }
        public string Allow_DESCRIPTION { get; set; }
        public string STA_DESCRIPTION { get; set; }
    }
}
