//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQUEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_sw_assets
    {
        public int SW_ID { get; set; }
        public string SW_CODE { get; set; }
        public string DEV_SW_CODE { get; set; }
        public string SW_ASSET { get; set; }
        public string SW_ASSET_NAME { get; set; }
        public string SW_YEAR { get; set; }
        public string SW_START_DATE { get; set; }
        public string SW_END_DATE { get; set; }
        public string SW_BRAND { get; set; }
        public string HW_SERIAL { get; set; }
        public string COST_ID { get; set; }
        public string SW_SERVICE_TAG { get; set; }
        public string SW_DESC_SHORT { get; set; }
        public string SW_DESCRIPT_LONG { get; set; }
        public string SW_PURCHASE_NO { get; set; }
        public string SW_PURCHASE_DATE { get; set; }
        public string SW_PICTURE { get; set; }
        public decimal SW_QTY { get; set; }
        public string SUPPLIER { get; set; }
        public int SW_WARANTEE { get; set; }
        public string DOC_NO { get; set; }
        public string SW_RENT { get; set; }
        public int ST_ID { get; set; }
        public string SW_REMARK { get; set; }
        public string USER_CREATE { get; set; }
        public string USER_UPDATE { get; set; }
        public string CREATE_DATE { get; set; }
        public string UPDATE_DATE { get; set; }
        public string DEV_SW_DESCRIPTION { get; set; }
        public string COSTCENTER { get; set; }
    }
}
