//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQUEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_it_open_by
    {
        public string EMP_NO { get; set; }
        public string IT_NAME { get; set; }
        public string IT_SURNAME { get; set; }
        public string INC_OPEN_BY { get; set; }
        public string INC_ASSIGN_TO { get; set; }
        public string EMP_NO_ASSIGN { get; set; }
        public string IT_NAME_ASSIGN { get; set; }
        public string IT_SURNAME_ASSIGN { get; set; }
    }
}
