//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQUEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Req_PG_Trace
    {
        public string Req_PG_CODE { get; set; }
        public string USER_NO { get; set; }
        public string USER_NAME { get; set; }
        public string NAME_ENG { get; set; }
        public string PROSITION { get; set; }
        public string DEPARTMENT { get; set; }
        public string USER_EXTENSION { get; set; }
        public Nullable<System.DateTime> PG_DATE { get; set; }
        public string PG_Work { get; set; }
        public string PG_Problem { get; set; }
        public string PG_Requirement { get; set; }
        public string PG_Frequency { get; set; }
        public Nullable<System.DateTime> PG_Date_start { get; set; }
        public string PG_APPROVER { get; set; }
        public string NAME_APPROVER { get; set; }
        public string PROSITION_APPROVER { get; set; }
        public string DEPARTMENT_APPROVER { get; set; }
        public string EXTENSION_APPROVER { get; set; }
        public Nullable<System.DateTime> PG_APPROVER_DATE { get; set; }
        public string Req_OPEN_BY { get; set; }
        public string NAME_OPEN { get; set; }
        public string SURNAME_OPEN { get; set; }
        public string EXTENSION_OPEN { get; set; }
        public Nullable<System.DateTime> Req_OPEN_DATE { get; set; }
        public Nullable<System.DateTime> Req_ASSIGN_TO_DATE { get; set; }
        public string Req_ASSIGN_TO { get; set; }
        public string NAME_ASSIGN { get; set; }
        public string SURNAME_ASSIGN { get; set; }
        public string EXTENSION_ASSIGN { get; set; }
        public string Req_CLOSE { get; set; }
        public string NAME_CLOSE { get; set; }
        public string SURNAME_CLOSE { get; set; }
        public string EXTENSION_CLOSE { get; set; }
        public Nullable<System.DateTime> Req_CLOSE_DATE { get; set; }
        public string REQ_STATUS { get; set; }
        public string STA_DESCRIPTION { get; set; }
        public string PG_APPROVER_IT { get; set; }
        public Nullable<System.DateTime> Date_APPROVER_IT { get; set; }
        public string NAME_APPROVER_IT { get; set; }
        public string SURNAME_APPROVER_IT { get; set; }
        public string EXTENSION_APPROVER_IT { get; set; }
    }
}
